// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Repos.Migrations
{
    [DbContext(typeof(AppDpContext))]
    [Migration("20210601105354_insertData")]
    partial class insertData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Department", b =>
                {
                    b.Property<int>("DeptNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Location")
                        .HasColumnType("int");

                    b.HasKey("DeptNo");

                    b.ToTable("Department");

                    b.HasData(
                        new
                        {
                            DeptNo = 1,
                            DeptName = "Smart Village Branch",
                            Location = 0
                        },
                        new
                        {
                            DeptNo = 2,
                            DeptName = "Alex Branch",
                            Location = 1
                        },
                        new
                        {
                            DeptNo = 3,
                            DeptName = "Suez Branch",
                            Location = 2
                        });
                });

            modelBuilder.Entity("Domain.Employee", b =>
                {
                    b.Property<int>("EmpNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DeptNo")
                        .HasColumnType("int");

                    b.Property<string>("Fname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("EmpNo");

                    b.HasIndex("DeptNo");

                    b.ToTable("Employee");

                    b.HasData(
                        new
                        {
                            EmpNo = 1,
                            DeptNo = 1,
                            Fname = "Ahmed",
                            Lname = "Mahmoud",
                            Salary = 10000m
                        },
                        new
                        {
                            EmpNo = 2,
                            DeptNo = 1,
                            Fname = "Ahmed",
                            Lname = "Mostafa",
                            Salary = 8000m
                        },
                        new
                        {
                            EmpNo = 3,
                            DeptNo = 1,
                            Fname = "Belal",
                            Lname = "Anan",
                            Salary = 8000m
                        },
                        new
                        {
                            EmpNo = 4,
                            DeptNo = 2,
                            Fname = "Mohamed",
                            Lname = "Moslem",
                            Salary = 11000m
                        },
                        new
                        {
                            EmpNo = 5,
                            DeptNo = 3,
                            Fname = "Mona",
                            Lname = "Hafez",
                            Salary = 12000m
                        });
                });

            modelBuilder.Entity("Domain.Project", b =>
                {
                    b.Property<int>("ProjectNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("Budget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectNo");

                    b.ToTable("Project");

                    b.HasData(
                        new
                        {
                            ProjectNo = 1,
                            Budget = 1000000m,
                            ProjectName = "Recycle Project"
                        },
                        new
                        {
                            ProjectNo = 2,
                            Budget = 20000000m,
                            ProjectName = "Developing Project"
                        });
                });

            modelBuilder.Entity("Domain.Works_on", b =>
                {
                    b.Property<int>("ProjectNo")
                        .HasColumnType("int");

                    b.Property<int>("EmpNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("Enter_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Job")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectNo", "EmpNo");

                    b.HasIndex("EmpNo");

                    b.ToTable("Works_on");

                    b.HasData(
                        new
                        {
                            ProjectNo = 1,
                            EmpNo = 1,
                            Enter_Date = new DateTime(2021, 6, 1, 12, 53, 53, 293, DateTimeKind.Local).AddTicks(6582),
                            Job = "Build the project"
                        },
                        new
                        {
                            ProjectNo = 1,
                            EmpNo = 2,
                            Enter_Date = new DateTime(2021, 6, 1, 12, 53, 53, 297, DateTimeKind.Local).AddTicks(3775),
                            Job = "Build the plan"
                        },
                        new
                        {
                            ProjectNo = 1,
                            EmpNo = 3,
                            Enter_Date = new DateTime(2021, 6, 1, 12, 53, 53, 297, DateTimeKind.Local).AddTicks(3803),
                            Job = "Start the project"
                        },
                        new
                        {
                            ProjectNo = 2,
                            EmpNo = 4,
                            Enter_Date = new DateTime(2021, 6, 1, 12, 53, 53, 297, DateTimeKind.Local).AddTicks(3806),
                            Job = "Build the project"
                        },
                        new
                        {
                            ProjectNo = 2,
                            EmpNo = 5,
                            Enter_Date = new DateTime(2021, 6, 1, 12, 53, 53, 297, DateTimeKind.Local).AddTicks(3808),
                            Job = "Build the project"
                        });
                });

            modelBuilder.Entity("Domain.Employee", b =>
                {
                    b.HasOne("Domain.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DeptNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Domain.Works_on", b =>
                {
                    b.HasOne("Domain.Employee", "Employee")
                        .WithMany("Works")
                        .HasForeignKey("EmpNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Project", "Project")
                        .WithMany("Works")
                        .HasForeignKey("ProjectNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Domain.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Domain.Employee", b =>
                {
                    b.Navigation("Works");
                });

            modelBuilder.Entity("Domain.Project", b =>
                {
                    b.Navigation("Works");
                });
#pragma warning restore 612, 618
        }
    }
}
